language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false

r:
  - release
  - devel

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev
  - sudo apt-get install -y gdal-bin
  - sudo apt-get install -y aria2
  - PATH="/usr/local/gdal/bin:$PATH"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

apt_packages:
    - libgdal-dev
    - libproj-dev
    - libcairo2-dev
    - libatk1.0-dev
    - libpango1.0-dev
    - libgtk2.0-dev
    - libglib2.0-dev
    - libcurl4-openssl-dev
    - libudunits2-dev
r_binary_packages:
    - cairoDevice
    - RGtk2
r_packages:
    - udunits2
    - units
    - covr
    - rgdal
    - sf
    - shiny
    - leaflet
    - mapview
    - mapedit
after_success:
  - Rscript -e 'library(covr);coveralls();codecov()'
